apiVersion: v1
kind: ConfigMap
metadata:
  name: heatguard-config
  namespace: heatguard
  labels:
    app.kubernetes.io/name: heatguard
    app.kubernetes.io/component: config
    app.kubernetes.io/version: "1.0.0"
data:
  # Application Configuration
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  API_V1_STR: "/api/v1"
  PROJECT_NAME: "HeatGuard Predictive Safety System"
  DESCRIPTION: "Production-grade heat exposure prediction API"
  VERSION: "1.0.0"

  # Server Configuration
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "4"
  RELOAD: "false"
  DEBUG: "false"

  # Performance Configuration
  BATCH_SIZE_LIMIT: "1000"
  RATE_LIMIT_PER_MINUTE: "1000"
  CONSERVATIVE_BIAS: "true"
  ENABLE_OSHA_LOGGING: "true"

  # CORS Configuration
  BACKEND_CORS_ORIGINS: '["https://dashboard.heatguard.com", "https://app.heatguard.com"]'

  # Cache Configuration
  CACHE_TTL_SECONDS: "300"

  # Model Configuration
  MODEL_DIR: "/app/thermal_comfort_model"
  MODEL_CACHE_SIZE: "10"

  # Monitoring Configuration
  METRICS_ENABLED: "true"
  HEALTH_CHECK_INTERVAL: "30"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: heatguard
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: config
    app.kubernetes.io/version: "7.0"
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    timeout 300
    tcp-keepalive 60
    daemonize no
    loglevel notice
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    rdbchecksum yes
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
    slowlog-log-slower-than 10000
    latency-monitor-threshold 100
    notify-keyspace-events Ex